### PR TITLE
Fix markdown for data tables

### LINKED ISSUE #66: Data tables render as uncommonly supported headerless tables
Data tables such as:

```gherkin
Feature: List of people
  Scenario: People are listed
    Given these folks
      | name | age |
      | dan  | 44  |
```

Are currently rendered like this:

```markdown
# List of people

## People are listed

_Given_ these folks

| name | age |
| dan  | 44  |
```

This format isn't supported by most Markdown parsers including GitHub's as you can see below.

---
---

# List of people

## People are listed

_Given_ these folks

| name | age |
| dan  | 44  |

---
---

## Proposal: Render multi-column data tables with implicit headers

What do you think about rendering multi-column data tables with implicit headers? In other words:

```markdown
| name | age |
| ---- | --- |
| dan  | 44  |
```

This would match the rendering of example tables and while the first row of a data table isn't strictly a header in step implementation, using a header is fairly common (see Cucumber's own [data table example](https://cucumber.io/docs/gherkin/reference/#data-tables)). At the very least, it would be parsed correctly by most Markdown parsers as a table.

## Proposal: Render single-column data tables as lists

For single column data tables, I see these used much more often as simple lists, so perhaps those could be rendered as Markdown lists. Alternately, you could also render these with implicit headers for consistency.

### PR DESCRIPTION
**Pull request by marxarelli**
Gherkin data tables can take a multitude of forms: simple lists or represent tabular data with no headers or headers along either axis (or both), while most markdown implementations only support tables with a header row. Omitting the header leads to markdown that cannot be fully converted to HTML.

Work around this incongruity by rendering all data tables as markdown tables with an empty header.

Fixes #66

### CODE REVIEW

File: renderer/renderer.go [hunk 1]
```diff
@@ -181,30 +186,45 @@ func (r renderer) renderExampleTable(h *messages.TableRow, rs []*messages.TableR
...
 
 	for _, r := range rs {
-		for i, c := range r.Cells {
-			if w := len(c.Value); w > ws[i] {
-				ws[i] = w
+		if r != nil {
+			for i, c := range r.Cells {
+				if w := len(c.Value); w > ws[i] {
+					ws[i] = w
+				}
```
Comment (raviqqe) [inline renderer/renderer.go:227]: @marxarelli Why is this change needed?

Comment (raviqqe) [reply renderer/renderer.go:227]: I figured that out! Actually, some tests were missing on CI.

**Comment by marxarelli** [comment]
Thanks for the merge and thanks for the really awesome tool! I'm using it to generate [example documentation](https://doc.wikimedia.org/releng/blubber/) for my own project.
